# This workflow will ensure all PRs are labeled so we can later create releases

name: PR labeling for release

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  ensure-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["PR: Bugfix ğŸ›", "PR: New Feature ğŸ•¹", "PR: Dependencies ğŸ› ", "PR: Documentation ğŸ“–", "PR: Internal ğŸ "]'
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Build output
      - name: Delete comment
        if: '${{ steps.check_pr_labels.outputs.result }}' == 'true'
        uses: jungwinter/comment@v1
        with:
          type: delete
          comment_id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create or update comment
        if: '${{ steps.check_pr_labels.outputs.result }}' == 'false'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Your PR should include one of the following labels:
              - PR: Bugfix ğŸ›
              - PR: New Feature ğŸ•¹
              - PR: Dependencies ğŸ› 
              - PR: Documentation ğŸ“–
              - PR: Internal ğŸ 
          edit-mode: replace
      - name: Fail
        if: '${{ steps.check_pr_labels.outputs.result }}' == 'false'
        run: exit 1
