# This workflow will ensure all PRs are labeled so we can later create releases

name: PR labeling for release

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  ensure-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels action step
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: '"PR: Bugfix ğŸ›", "PR: New Feature ğŸ•¹", "PR: Dependencies ğŸ› ", "PR: Documentation ğŸ“–", "PR: Internal ğŸ "'
