name: Publish Storybooks

on:
  workflow_run:
    workflows: ["Release new version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{ secrets.npm_token }}
      - name: Build & deploy Storybooks to GitHub Pages
        run: |
          yarn lerna run build --include-dependencies
          yarn lerna run --scope @vibe/docs build-storybook
          cd packages/docs/static_storybook
          echo "vibe.monday.com" > ./CNAME
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - name: Push core Storybook to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean-exclude: |
            v2/*
            playground/*
          folder: packages/docs/static_storybook
          branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
